@api = http://localhost:4000/usuarios

GET  {{api}}
###
GET {{api}}/5

###
POST {{api}}
Content-Type: application/json

{
        "name":"nombre2",
        "lastName":"apellido2",
        "username": "usuario2",
        "password": "contraseña2",
        "cellphone":"cellphone2",
        "mail":"ejemplo2@gmail.com",
        "description": "descripcion2",
        "profilePicture": "pfp2",
        "premium": 1,
        "occupation": "ocupacion2"
}
###

DELETE {{api}}/4

###
PUT {{api}}/6
Content-Type:application/json

{
        "username": "usuarioactualizado",
        "password": "yfkufjuyrdjfd",
        "works": 0,
        "mail":"turiufkv@gmail.com",
        "followers": 0,
        "follows": 0,
        "premium": 0,
        "occupation": "khgkutfyhr",
        "profilePicture": "tyeruytjgkvjh",  
        "description": "mvvdssdfg"
}

